name: Telegram Notifications

on:
  push:
    branches: [ dev ]
  pull_request:
    types: [ closed ]
    branches: [ dev ]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get commit details
        id: commit-details
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
            echo "author=$(git log -1 --pretty=%an)" >> $GITHUB_OUTPUT
            echo "event_type=푸시됨" >> $GITHUB_OUTPUT
            echo "url=${{ github.event.head_commit.url }}" >> $GITHUB_OUTPUT
          else
            echo "message=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
            echo "author=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT
            echo "event_type=병합됨" >> $GITHUB_OUTPUT
            echo "url=${{ github.event.pull_request.html_url }}" >> $GITHUB_OUTPUT
          fi

      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            🔔 *${{ github.repository }}* 레포지토리 알림
            
            👤 사용자: *${{ steps.commit-details.outputs.author }}*
            📝 이벤트: *${{ steps.commit-details.outputs.event_type }}*
            📝 메시지: ${{ steps.commit-details.outputs.message }}
            🔗 [상세 정보 보기](${{ steps.commit-details.outputs.url }})